AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/IndentationWidth:
  Width: 2

Layout/TrailingWhitespace:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
